name: MetricsExperiment .NET

on:
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]
  [workflow_dispatch]

jobs:
  build:
    name: "Build ${{ github.repository }} ${{ github.ref_name }}"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore MetricsExperiment/MetricsExperiment.sln
      
    - name: Build
      run: dotnet build MetricsExperiment/MetricsExperiment.sln --no-restore

    - name: Test
      run: dotnet test MetricsExperiment/MetricsExperiment.sln --no-build --verbosity normal

    - name: SonarQube Scan
      # You may pin to the exact commit or the version.
      # uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
      uses: SonarSource/sonarqube-scan-action@v1.1.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      with:
        # Additional arguments to the sonar-scanner
        #args: > # optional
        #  -Dsonar.python.coverage.reportPaths=coverage.xml
        #  -Dsonar.tests=tests/
        #  -Dsonar.verbose=true
        # Set the sonar.projectBaseDir analysis property
        projectBaseDir: MetricsExperiment/# optional, default is .
              
    
